/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import conexion_y_funciones.Funciones;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.PasswordView;
/**
 *
 * @author Usuario
 */
public class GestionUsuarioGerente extends javax.swing.JPanel {
    Funciones funciones = new Funciones();
    DefaultTableModel model;    
    /**
     * Creates new form GestionUsuarioGerente
     */
    
    public void addPlaceholder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    public void removePlaceholder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
    public GestionUsuarioGerente() {
        initComponents();
        //inicializa con las sedes
        funciones.consultar_sedes_combo(jComboBox13);
        funciones.consultar_sedes_combo(jComboBox15);
        
        
        //inicializa con los roles
        funciones.consultar_roles_combo(jComboBox14);
        funciones.consultar_roles_combo(jComboBox16);
        
        //Inicializa con los estados
        funciones.consultar_estados_combo(jComboBox17);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator61 = new javax.swing.JSeparator();
        campo_documentoId = new javax.swing.JTextField();
        jSeparator62 = new javax.swing.JSeparator();
        campo_nombre = new javax.swing.JTextField();
        jSeparator63 = new javax.swing.JSeparator();
        campo_segundoApellido = new javax.swing.JTextField();
        campo_primerApellido = new javax.swing.JTextField();
        jSeparator64 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        jSeparator65 = new javax.swing.JSeparator();
        campo_telefono = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jSeparator66 = new javax.swing.JSeparator();
        jSeparator67 = new javax.swing.JSeparator();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        campo_correo = new javax.swing.JTextField();
        jSeparator68 = new javax.swing.JSeparator();
        jPasswordField13 = new javax.swing.JPasswordField();
        jSeparator69 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator70 = new javax.swing.JSeparator();
        jPasswordField14 = new javax.swing.JPasswordField();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator71 = new javax.swing.JSeparator();
        buscar_documentoId = new javax.swing.JTextField();
        jSeparator72 = new javax.swing.JSeparator();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        editar_nombre = new javax.swing.JTextField();
        jSeparator75 = new javax.swing.JSeparator();
        editar_documentoId = new javax.swing.JTextField();
        jSeparator76 = new javax.swing.JSeparator();
        editar_primerApellido = new javax.swing.JTextField();
        jSeparator77 = new javax.swing.JSeparator();
        editar_segundoApellido = new javax.swing.JTextField();
        jSeparator78 = new javax.swing.JSeparator();
        editar_telefono = new javax.swing.JTextField();
        jSeparator79 = new javax.swing.JSeparator();
        jComboBox15 = new javax.swing.JComboBox<>();
        jSeparator80 = new javax.swing.JSeparator();
        jComboBox16 = new javax.swing.JComboBox<>();
        jSeparator81 = new javax.swing.JSeparator();
        editar_correo = new javax.swing.JTextField();
        jSeparator82 = new javax.swing.JSeparator();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jComboBox17 = new javax.swing.JComboBox<>();
        jSeparator83 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(597, 690));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/agregarUs.png"))); // NOI18N

        campo_documentoId.setForeground(new java.awt.Color(153, 153, 153));
        campo_documentoId.setText("Documento de identificación");
        campo_documentoId.setBorder(null);
        campo_documentoId.setPreferredSize(new java.awt.Dimension(7, 24));
        campo_documentoId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_documentoIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_documentoIdFocusLost(evt);
            }
        });

        campo_nombre.setForeground(new java.awt.Color(153, 153, 153));
        campo_nombre.setText("Nombre");
        campo_nombre.setBorder(null);
        campo_nombre.setPreferredSize(new java.awt.Dimension(7, 24));
        campo_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_nombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_nombreFocusLost(evt);
            }
        });

        campo_segundoApellido.setForeground(new java.awt.Color(153, 153, 153));
        campo_segundoApellido.setText("Segundo apellido");
        campo_segundoApellido.setBorder(null);
        campo_segundoApellido.setPreferredSize(new java.awt.Dimension(7, 24));
        campo_segundoApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_segundoApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_segundoApellidoFocusLost(evt);
            }
        });

        campo_primerApellido.setForeground(new java.awt.Color(153, 153, 153));
        campo_primerApellido.setText("Primer apellido");
        campo_primerApellido.setBorder(null);
        campo_primerApellido.setPreferredSize(new java.awt.Dimension(7, 24));
        campo_primerApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_primerApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_primerApellidoFocusLost(evt);
            }
        });
        campo_primerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_primerApellidojTextField4ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Datos personales:");

        campo_telefono.setForeground(new java.awt.Color(153, 153, 153));
        campo_telefono.setText("Teléfono");
        campo_telefono.setBorder(null);
        campo_telefono.setPreferredSize(new java.awt.Dimension(7, 24));
        campo_telefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_telefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_telefonoFocusLost(evt);
            }
        });
        campo_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_telefonojTextField5ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Datos empleado:");

        jComboBox13.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox13MouseClicked(evt);
            }
        });
        jComboBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox13ActionPerformed(evt);
            }
        });

        jComboBox14.setForeground(new java.awt.Color(153, 153, 153));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel40.setText("Crear cuenta:");

        campo_correo.setForeground(new java.awt.Color(153, 153, 153));
        campo_correo.setText("Correo");
        campo_correo.setBorder(null);
        campo_correo.setPreferredSize(new java.awt.Dimension(7, 24));
        campo_correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_correoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_correoFocusLost(evt);
            }
        });
        campo_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_correojTextField6ActionPerformed(evt);
            }
        });

        jPasswordField13.setText("jPasswordField1");
        jPasswordField13.setBorder(null);
        jPasswordField13.setMinimumSize(new java.awt.Dimension(10, 20));
        jPasswordField13.setPreferredSize(new java.awt.Dimension(112, 24));
        jPasswordField13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField13jPasswordField1MouseClicked(evt);
            }
        });

        jLabel41.setText("Contraseña:");

        jLabel42.setText("Comfirmar contraseña:");

        jPasswordField14.setText("jPasswordField1");
        jPasswordField14.setBorder(null);
        jPasswordField14.setMinimumSize(new java.awt.Dimension(10, 20));
        jPasswordField14.setPreferredSize(new java.awt.Dimension(112, 24));
        jPasswordField14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField14jPasswordField2MouseClicked(evt);
            }
        });

        jButton10.setText("REGISTRAR");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel40)
                .addGap(126, 126, 126))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37)
                .addGap(200, 200, 200))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campo_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator62, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campo_documentoId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator61, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campo_segundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator63, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campo_primerApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator64, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campo_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator65, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator67)
                        .addComponent(jSeparator66)
                        .addComponent(jComboBox13, 0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox14, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campo_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPasswordField13, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator69, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jPasswordField14, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator70, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator68, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jLabel40))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(campo_documentoId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator61, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(campo_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator68, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator62, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(campo_primerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator64, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPasswordField13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator69, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_segundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addGap(0, 0, 0)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jSeparator63, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPasswordField14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator70, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addComponent(jSeparator65, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jSeparator66, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator67, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel9);

        jTabbedPane1.addTab("REGISTRAR USUARIO", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Por favor ingrese el número de identificación");

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/lupa.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("del usuario que desea consultar:");

        buscar_documentoId.setForeground(new java.awt.Color(153, 153, 153));
        buscar_documentoId.setText("Documento de identificación");
        buscar_documentoId.setBorder(null);
        buscar_documentoId.setPreferredSize(new java.awt.Dimension(7, 24));
        buscar_documentoId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscar_documentoIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscar_documentoIdFocusLost(evt);
            }
        });

        jButton11.setText("CONSULTAR");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("VER BASE DE DATOS");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jTable1.setModel(jTable1.getModel());
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator72)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscar_documentoId, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addGap(101, 101, 101)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscar_documentoId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator72, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jPanel4.add(jPanel1);

        jTabbedPane1.addTab("CONSULTAR USUARIO", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Número de identificación del usuario a modificar:");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Datos personales:");

        editar_nombre.setForeground(new java.awt.Color(153, 153, 153));
        editar_nombre.setText("Nombre");
        editar_nombre.setBorder(null);
        editar_nombre.setPreferredSize(new java.awt.Dimension(7, 24));
        editar_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editar_nombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editar_nombreFocusLost(evt);
            }
        });

        editar_documentoId.setForeground(new java.awt.Color(153, 153, 153));
        editar_documentoId.setText("Documento de identificación");
        editar_documentoId.setBorder(null);
        editar_documentoId.setPreferredSize(new java.awt.Dimension(7, 24));
        editar_documentoId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editar_documentoIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editar_documentoIdFocusLost(evt);
            }
        });

        editar_primerApellido.setForeground(new java.awt.Color(153, 153, 153));
        editar_primerApellido.setText("Primer apellido");
        editar_primerApellido.setBorder(null);
        editar_primerApellido.setPreferredSize(new java.awt.Dimension(7, 24));
        editar_primerApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editar_primerApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editar_primerApellidoFocusLost(evt);
            }
        });

        editar_segundoApellido.setForeground(new java.awt.Color(153, 153, 153));
        editar_segundoApellido.setText("Segundo apellido");
        editar_segundoApellido.setBorder(null);
        editar_segundoApellido.setPreferredSize(new java.awt.Dimension(7, 24));
        editar_segundoApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editar_segundoApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editar_segundoApellidoFocusLost(evt);
            }
        });

        editar_telefono.setForeground(new java.awt.Color(153, 153, 153));
        editar_telefono.setText("Teléfono");
        editar_telefono.setBorder(null);
        editar_telefono.setPreferredSize(new java.awt.Dimension(7, 24));
        editar_telefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editar_telefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editar_telefonoFocusLost(evt);
            }
        });
        editar_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_telefonoActionPerformed(evt);
            }
        });

        jComboBox15.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox15MouseClicked(evt);
            }
        });
        jComboBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox15ActionPerformed(evt);
            }
        });

        jComboBox16.setForeground(new java.awt.Color(153, 153, 153));

        editar_correo.setForeground(new java.awt.Color(153, 153, 153));
        editar_correo.setText("Correo");
        editar_correo.setBorder(null);
        editar_correo.setPreferredSize(new java.awt.Dimension(7, 24));
        editar_correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editar_correoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editar_correoFocusLost(evt);
            }
        });
        editar_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_correoActionPerformed(evt);
            }
        });

        jButton14.setText("MOSTRAR DATOS");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("GUARDAR CAMBIOS");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        jButton16.setText("CAMBIAR CONTRASEÑA");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton16MouseClicked(evt);
            }
        });
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jComboBox17.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox17.setToolTipText("");
        jComboBox17.setName(""); // NOI18N
        jComboBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox17ActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("Estado en la empresa:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel45)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editar_documentoId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator76, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator81)
                                        .addComponent(jSeparator80)
                                        .addComponent(jComboBox16, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox15, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(editar_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator75)
                                        .addComponent(editar_segundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator78)
                                        .addComponent(editar_primerApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator77)
                                        .addComponent(editar_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator79)
                                        .addComponent(editar_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator82, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel46))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator83)
                            .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editar_documentoId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addGap(0, 0, 0)
                .addComponent(jSeparator76, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(editar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator75, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator83, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_primerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator77, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_segundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator78, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator79, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator82, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator80, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator81, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jComboBox17.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("EDITAR USUARIO", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campo_primerApellidojTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_primerApellidojTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_primerApellidojTextField4ActionPerformed

    private void campo_telefonojTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_telefonojTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_telefonojTextField5ActionPerformed

    private void campo_correojTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_correojTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_correojTextField6ActionPerformed

    private void jPasswordField13jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField13jPasswordField1MouseClicked
        // TODO add your handling code here:
        jPasswordField13.setText(null);
    }//GEN-LAST:event_jPasswordField13jPasswordField1MouseClicked

    private void jPasswordField14jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField14jPasswordField2MouseClicked
        // TODO add your handling code here:
        jPasswordField14.setText(null);
    }//GEN-LAST:event_jPasswordField14jPasswordField2MouseClicked

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void jTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField37ActionPerformed

    private void jComboBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox14ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        String sede = (String) jComboBox13.getSelectedItem();
        String rol = (String) jComboBox14.getSelectedItem();
        String documento = campo_documentoId.getText();
        String nombre = campo_nombre.getText();
        String apellido1 = campo_primerApellido.getText();
        String apellido2 = campo_segundoApellido.getText();
        String telefono = campo_telefono.getText();
        String correo = campo_correo.getText();
        char[] clave = jPasswordField13.getPassword();
        char[] claveConfirm = jPasswordField14.getPassword();
        
        
        String[] partsSede = sede.split("//");
        String claveConv = new String(clave);
        String claveConfirmConv = new String(claveConfirm);
        
        if (claveConv.equals(claveConfirmConv)){
            funciones.registrarUsuario(documento, partsSede[0],partsSede[1],partsSede[2], rol, "activo", nombre, apellido1, apellido2, telefono, correo, claveConv);
        }else{
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }
        

    }//GEN-LAST:event_jButton10MouseClicked

    private void editar_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editar_telefonoActionPerformed

    private void editar_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editar_correoActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jComboBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox15ActionPerformed

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        // TODO add your handling code here:
        
        String documentoConsult = editar_documentoId.getText();
        funciones.consultar_datos_usuario(documentoConsult, editar_nombre, editar_primerApellido, editar_segundoApellido, editar_telefono, editar_correo, jComboBox15, jComboBox16, jComboBox17);
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
      funciones.creartabla(jTable1);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
      String documento = buscar_documentoId.getText();
      funciones.creartablausuario(jTable1, documento);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        String documento = editar_documentoId.getText();
        String nombre = editar_nombre.getText();
        String apellido1 = editar_primerApellido.getText();
        String apellido2 = editar_segundoApellido.getText();
        String telefono = editar_telefono.getText();
        String correo = editar_correo.getText();
        String sede = (String) jComboBox15.getSelectedItem();
        String rol = (String) jComboBox16.getSelectedItem();
        String estado = (String) jComboBox17.getSelectedItem();
        String[] partsSede = sede.split("//");
        funciones.editarUsuario(documento, nombre, apellido1, apellido2, telefono, correo, partsSede[0],partsSede[1],partsSede[2], rol, estado);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jComboBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox17ActionPerformed

    private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
        String documento = editar_documentoId.getText();
        JPasswordField pf = new JPasswordField();
        JPasswordField pf2 = new JPasswordField();
        int opcion1 = JOptionPane.showConfirmDialog(null, pf, "Ingresa la contraseña actual", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (opcion1 == JOptionPane.OK_OPTION){
        String password = new String(pf.getPassword());        
        if((funciones.consultarContraseña(documento, password)).equals(password)){
            int opcion2 = JOptionPane.showConfirmDialog(null, pf2, "Correcto. Ingresa la nueva contraseña", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (opcion2 == JOptionPane.OK_OPTION){
                String newpassword = new String(pf2.getPassword());
                if ((newpassword.equals(""))||(newpassword.equals(password))){
                    JOptionPane.showMessageDialog(null, "La contraseña es la misma o esta vacia", "La contraseña no fue actualizada", JOptionPane.ERROR_MESSAGE);
                    }else{
                        funciones.editarContraseña(documento, newpassword);
                    }                
                }
            }else{
            JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
        }        
    }//GEN-LAST:event_jButton16MouseClicked

    private void jComboBox13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox13MouseClicked
        jComboBox13.removeAllItems();
        funciones.consultar_sedes_combo(jComboBox13);
    }//GEN-LAST:event_jComboBox13MouseClicked

    private void jComboBox15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox15MouseClicked
        jComboBox15.removeAllItems();
        funciones.consultar_sedes_combo(jComboBox15);
    }//GEN-LAST:event_jComboBox15MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void campo_documentoIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_documentoIdFocusGained
         if(campo_documentoId.getText().equals("Documento de identificación")){
            campo_documentoId.setText(null);
            campo_documentoId.requestFocus();
            // quitar place holder
            removePlaceholder(campo_documentoId);
        }
    }//GEN-LAST:event_campo_documentoIdFocusGained

    private void campo_documentoIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_documentoIdFocusLost
        if(campo_documentoId.getText().length() == 0){
            addPlaceholder(campo_documentoId);
            campo_documentoId.setText("Documento de identificación");
        }
    }//GEN-LAST:event_campo_documentoIdFocusLost

    private void campo_nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_nombreFocusGained
        if(campo_nombre.getText().equals("Nombre")){
            campo_nombre.setText(null);
            campo_nombre.requestFocus();
            // quitar place holder
            removePlaceholder(campo_nombre);
        }
    }//GEN-LAST:event_campo_nombreFocusGained

    private void campo_nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_nombreFocusLost
        if(campo_nombre.getText().length() == 0){
            addPlaceholder(campo_nombre);
            campo_nombre.setText("Nombre");
        }
    }//GEN-LAST:event_campo_nombreFocusLost

    private void campo_primerApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_primerApellidoFocusGained
        if(campo_primerApellido.getText().equals("Primer apellido")){
            campo_primerApellido.setText(null);
            campo_primerApellido.requestFocus();
            // quitar place holder
            removePlaceholder(campo_primerApellido);
        }
    }//GEN-LAST:event_campo_primerApellidoFocusGained

    private void campo_primerApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_primerApellidoFocusLost
        if(campo_primerApellido.getText().length() == 0){
            addPlaceholder(campo_primerApellido);
            campo_primerApellido.setText("Primer apellido");
        }
    }//GEN-LAST:event_campo_primerApellidoFocusLost

    private void campo_segundoApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_segundoApellidoFocusGained
        if(campo_segundoApellido.getText().equals("Segundo apellido")){
            campo_segundoApellido.setText(null);
            campo_segundoApellido.requestFocus();
            // quitar place holder
            removePlaceholder(campo_segundoApellido);
        }
    }//GEN-LAST:event_campo_segundoApellidoFocusGained

    private void campo_segundoApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_segundoApellidoFocusLost
        if(campo_segundoApellido.getText().length() == 0){
            addPlaceholder(campo_segundoApellido);
            campo_segundoApellido.setText("Segundo apellido");
        }
    }//GEN-LAST:event_campo_segundoApellidoFocusLost

    private void campo_telefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_telefonoFocusGained
        if(campo_telefono.getText().equals("Teléfono")){
            campo_telefono.setText(null);
            campo_telefono.requestFocus();
            // quitar place holder
            removePlaceholder(campo_telefono);
        }
    }//GEN-LAST:event_campo_telefonoFocusGained

    private void campo_telefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_telefonoFocusLost
        if(campo_telefono.getText().length() == 0){
            addPlaceholder(campo_telefono);
            campo_telefono.setText("Teléfono");
        }
    }//GEN-LAST:event_campo_telefonoFocusLost

    private void campo_correoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_correoFocusGained
        if(campo_correo.getText().equals("Correo")){
            campo_correo.setText(null);
            campo_correo.requestFocus();
            // quitar place holder
            removePlaceholder(campo_correo);
        }
    }//GEN-LAST:event_campo_correoFocusGained

    private void campo_correoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_correoFocusLost
        if(campo_correo.getText().length() == 0){
            addPlaceholder(campo_correo);
            campo_correo.setText("Correo");
        }
    }//GEN-LAST:event_campo_correoFocusLost

    private void buscar_documentoIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscar_documentoIdFocusGained
        if(buscar_documentoId.getText().equals("Documento de identificación")){
            buscar_documentoId.setText(null);
            buscar_documentoId.requestFocus();
            // quitar place holder
            removePlaceholder(buscar_documentoId);
        }
    }//GEN-LAST:event_buscar_documentoIdFocusGained

    private void buscar_documentoIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscar_documentoIdFocusLost
        if(buscar_documentoId.getText().length() == 0){
            addPlaceholder(buscar_documentoId);
            buscar_documentoId.setText("Documento de identificación");
        }
    }//GEN-LAST:event_buscar_documentoIdFocusLost

    private void editar_documentoIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_documentoIdFocusGained
        if(editar_documentoId.getText().equals("Documento de identificación")){
            editar_documentoId.setText(null);
            editar_documentoId.requestFocus();
            // quitar place holder
            removePlaceholder(editar_documentoId);
        }
    }//GEN-LAST:event_editar_documentoIdFocusGained

    private void editar_documentoIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_documentoIdFocusLost
        if(editar_documentoId.getText().length() == 0){
            addPlaceholder(editar_documentoId);
            editar_documentoId.setText("Documento de identificación");
        }
    }//GEN-LAST:event_editar_documentoIdFocusLost

    private void editar_nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_nombreFocusGained
        if(editar_nombre.getText().equals("Nombre")){
            editar_nombre.setText(null);
            editar_nombre.requestFocus();
            // quitar place holder
            removePlaceholder(editar_nombre);
        }
    }//GEN-LAST:event_editar_nombreFocusGained

    private void editar_nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_nombreFocusLost
        if(editar_nombre.getText().length() == 0){
            addPlaceholder(editar_nombre);
            editar_nombre.setText("Nombre");
        }
    }//GEN-LAST:event_editar_nombreFocusLost

    private void editar_primerApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_primerApellidoFocusGained
        if(editar_primerApellido.getText().equals("Primer apellido")){
            editar_primerApellido.setText(null);
            editar_primerApellido.requestFocus();
            // quitar place holder
            removePlaceholder(editar_primerApellido);
        }
    }//GEN-LAST:event_editar_primerApellidoFocusGained

    private void editar_primerApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_primerApellidoFocusLost
        if(editar_primerApellido.getText().length() == 0){
            addPlaceholder(editar_primerApellido);
            editar_primerApellido.setText("Primer apellido");
        }
    }//GEN-LAST:event_editar_primerApellidoFocusLost

    private void editar_segundoApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_segundoApellidoFocusGained
        if(editar_segundoApellido.getText().equals("Segundo apellido")){
            editar_segundoApellido.setText(null);
            editar_segundoApellido.requestFocus();
            // quitar place holder
            removePlaceholder(editar_segundoApellido);
        }
    }//GEN-LAST:event_editar_segundoApellidoFocusGained

    private void editar_segundoApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_segundoApellidoFocusLost
        if(editar_segundoApellido.getText().length() == 0){
            addPlaceholder(editar_segundoApellido);
            editar_segundoApellido.setText("Segundo apellido");
        }
    }//GEN-LAST:event_editar_segundoApellidoFocusLost

    private void editar_telefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_telefonoFocusGained
        if(editar_telefono.getText().equals("Teléfono")){
            editar_telefono.setText(null);
            editar_telefono.requestFocus();
            // quitar place holder
            removePlaceholder(editar_telefono);
        }
    }//GEN-LAST:event_editar_telefonoFocusGained

    private void editar_telefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_telefonoFocusLost
        if(editar_telefono.getText().length() == 0){
            addPlaceholder(editar_telefono);
            editar_telefono.setText("Teléfono");
        }
    }//GEN-LAST:event_editar_telefonoFocusLost

    private void editar_correoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_correoFocusGained
        if(editar_correo.getText().equals("Correo")){
            editar_correo.setText(null);
            editar_correo.requestFocus();
            // quitar place holder
            removePlaceholder(editar_correo);
        }
    }//GEN-LAST:event_editar_correoFocusGained

    private void editar_correoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_correoFocusLost
        if(editar_correo.getText().length() == 0){
            addPlaceholder(editar_correo);
            editar_correo.setText("Correo");
        }
    }//GEN-LAST:event_editar_correoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar_documentoId;
    private javax.swing.JTextField campo_correo;
    private javax.swing.JTextField campo_documentoId;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_primerApellido;
    private javax.swing.JTextField campo_segundoApellido;
    private javax.swing.JTextField campo_telefono;
    private javax.swing.JTextField editar_correo;
    private javax.swing.JTextField editar_documentoId;
    private javax.swing.JTextField editar_nombre;
    private javax.swing.JTextField editar_primerApellido;
    private javax.swing.JTextField editar_segundoApellido;
    private javax.swing.JTextField editar_telefono;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField13;
    private javax.swing.JPasswordField jPasswordField14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    private javax.swing.JSeparator jSeparator64;
    private javax.swing.JSeparator jSeparator65;
    private javax.swing.JSeparator jSeparator66;
    private javax.swing.JSeparator jSeparator67;
    private javax.swing.JSeparator jSeparator68;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JSeparator jSeparator70;
    private javax.swing.JSeparator jSeparator71;
    private javax.swing.JSeparator jSeparator72;
    private javax.swing.JSeparator jSeparator75;
    private javax.swing.JSeparator jSeparator76;
    private javax.swing.JSeparator jSeparator77;
    private javax.swing.JSeparator jSeparator78;
    private javax.swing.JSeparator jSeparator79;
    private javax.swing.JSeparator jSeparator80;
    private javax.swing.JSeparator jSeparator81;
    private javax.swing.JSeparator jSeparator82;
    private javax.swing.JSeparator jSeparator83;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
