/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

    import conexion_y_funciones.Funciones;
import java.awt.Color;
import java.awt.Font;
    import java.awt.event.ActionEvent;
    import java.sql.Connection;
    import java.sql.ResultSet;
    import java.sql.Statement;
    import javax.swing.JOptionPane;
import javax.swing.JTextField;
    import javax.swing.table.DefaultTableModel;

public class GestionSedeGerente extends javax.swing.JPanel {

    Funciones funciones = new Funciones();
    
    //Añadir placeholder a los textfield
    public void addPlaceholder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    //Quitar placeholder a los textfield
    public void removePlaceholder(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }
    
    public GestionSedeGerente() {
        initComponents();
        jComboBox13.removeAllItems();
        jComboBox14.removeAllItems();
        funciones.consultar_sedes_combo(jComboBox13);
        funciones.consultar_sedes_combo(jComboBox14);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator61 = new javax.swing.JSeparator();
        campo_ciudad = new javax.swing.JTextField();
        jSeparator62 = new javax.swing.JSeparator();
        campo_barrio = new javax.swing.JTextField();
        jSeparator63 = new javax.swing.JSeparator();
        campo_telefono = new javax.swing.JTextField();
        campo_direccion = new javax.swing.JTextField();
        jSeparator64 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator71 = new javax.swing.JSeparator();
        buscar_sede = new javax.swing.JTextField();
        jSeparator72 = new javax.swing.JSeparator();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jSeparator83 = new javax.swing.JSeparator();
        buscar_barrio = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator73 = new javax.swing.JSeparator();
        jButton13 = new javax.swing.JButton();
        jComboBox13 = new javax.swing.JComboBox<>();
        jSeparator66 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        editar_barrio = new javax.swing.JTextField();
        jSeparator75 = new javax.swing.JSeparator();
        editar_direccion = new javax.swing.JTextField();
        jSeparator77 = new javax.swing.JSeparator();
        editar_ciudad = new javax.swing.JTextField();
        jSeparator78 = new javax.swing.JSeparator();
        editar_telefono = new javax.swing.JTextField();
        jSeparator79 = new javax.swing.JSeparator();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jComboBox14 = new javax.swing.JComboBox<>();

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(597, 690));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/iconoSede.png"))); // NOI18N

        jSeparator61.setBackground(new java.awt.Color(0, 0, 0));

        campo_ciudad.setForeground(new java.awt.Color(153, 153, 153));
        campo_ciudad.setText("Ciudad");
        campo_ciudad.setBorder(null);
        campo_ciudad.setPreferredSize(new java.awt.Dimension(7, 24));
        campo_ciudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_ciudadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_ciudadFocusLost(evt);
            }
        });

        jSeparator62.setBackground(new java.awt.Color(0, 0, 0));

        campo_barrio.setForeground(new java.awt.Color(153, 153, 153));
        campo_barrio.setText("Barrio");
        campo_barrio.setBorder(null);
        campo_barrio.setPreferredSize(new java.awt.Dimension(7, 24));
        campo_barrio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_barrioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_barrioFocusLost(evt);
            }
        });

        jSeparator63.setBackground(new java.awt.Color(0, 0, 0));

        campo_telefono.setForeground(new java.awt.Color(153, 153, 153));
        campo_telefono.setText("Número de teléfono");
        campo_telefono.setBorder(null);
        campo_telefono.setPreferredSize(new java.awt.Dimension(7, 24));
        campo_telefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_telefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_telefonoFocusLost(evt);
            }
        });

        campo_direccion.setForeground(new java.awt.Color(153, 153, 153));
        campo_direccion.setText("Dirección");
        campo_direccion.setBorder(null);
        campo_direccion.setPreferredSize(new java.awt.Dimension(7, 24));
        campo_direccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campo_direccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campo_direccionFocusLost(evt);
            }
        });
        campo_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_direccionjTextField4ActionPerformed(evt);
            }
        });

        jSeparator64.setBackground(new java.awt.Color(0, 0, 0));

        jButton10.setText("REGISTRAR");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("Datos de la sede:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(107, 145, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campo_barrio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator62, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campo_ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator61, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campo_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator63, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(campo_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator64, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(145, 145, 145))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel47)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(campo_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator61, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator62, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator64, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator63, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel3.add(jPanel9);

        jTabbedPane1.addTab("REGISTRAR SEDE", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(462, 480));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Consultar por barrio:");

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/lupa.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Consultar por ciudad:");

        jSeparator71.setBackground(new java.awt.Color(0, 0, 0));

        buscar_sede.setForeground(new java.awt.Color(153, 153, 153));
        buscar_sede.setText("Ciudad de la sede");
        buscar_sede.setBorder(null);
        buscar_sede.setPreferredSize(new java.awt.Dimension(7, 24));
        buscar_sede.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscar_sedeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscar_sedeFocusLost(evt);
            }
        });

        jSeparator72.setBackground(new java.awt.Color(0, 0, 0));

        jButton11.setText("IR");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("VER BASE DE DATOS");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jSeparator83.setBackground(new java.awt.Color(0, 0, 0));

        buscar_barrio.setForeground(new java.awt.Color(153, 153, 153));
        buscar_barrio.setText("Barrio de la sede");
        buscar_barrio.setBorder(null);
        buscar_barrio.setPreferredSize(new java.awt.Dimension(7, 24));
        buscar_barrio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscar_barrioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscar_barrioFocusLost(evt);
            }
        });

        jButton17.setText("IR");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });

        jTable1.setModel(jTable1.getModel());
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Barrio");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Direccion");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Ciudad");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Telefono");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(13, 13, 13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator83)
                                .addComponent(buscar_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator72)
                                .addComponent(buscar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buscar_sede, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator72, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buscar_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, 0)
                                .addComponent(jSeparator83, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1);

        jTabbedPane1.addTab("CONSULTAR SEDE", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(462, 425));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Por favor seleccione la sede que desea ");

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/eliminarSede.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("eliminar de la base de datos:");

        jSeparator73.setBackground(new java.awt.Color(0, 0, 0));

        jButton13.setText("ELIMINAR");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        jComboBox13.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione sede" }));
        jComboBox13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox13MouseClicked(evt);
            }
        });

        jSeparator66.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 116, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator66)
                                .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(149, 149, 149))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel44))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel44)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator66, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jPanel6.add(jPanel2);

        jTabbedPane1.addTab("ELIMINAR SEDE", jPanel6);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Sede a modificar:");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Datos de la sede:");

        editar_barrio.setForeground(new java.awt.Color(153, 153, 153));
        editar_barrio.setText("Barrio");
        editar_barrio.setBorder(null);
        editar_barrio.setPreferredSize(new java.awt.Dimension(7, 24));
        editar_barrio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editar_barrioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editar_barrioFocusLost(evt);
            }
        });

        jSeparator75.setBackground(new java.awt.Color(0, 0, 0));

        editar_direccion.setForeground(new java.awt.Color(153, 153, 153));
        editar_direccion.setText("Dirección");
        editar_direccion.setBorder(null);
        editar_direccion.setPreferredSize(new java.awt.Dimension(7, 24));
        editar_direccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editar_direccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editar_direccionFocusLost(evt);
            }
        });
        editar_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_direccionjTextField4ActionPerformed(evt);
            }
        });

        jSeparator77.setBackground(new java.awt.Color(0, 0, 0));

        editar_ciudad.setForeground(new java.awt.Color(153, 153, 153));
        editar_ciudad.setText("Ciudad");
        editar_ciudad.setBorder(null);
        editar_ciudad.setPreferredSize(new java.awt.Dimension(7, 24));
        editar_ciudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editar_ciudadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editar_ciudadFocusLost(evt);
            }
        });

        jSeparator78.setBackground(new java.awt.Color(0, 0, 0));

        editar_telefono.setForeground(new java.awt.Color(153, 153, 153));
        editar_telefono.setText("Número de teléfono");
        editar_telefono.setBorder(null);
        editar_telefono.setPreferredSize(new java.awt.Dimension(7, 24));
        editar_telefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editar_telefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                editar_telefonoFocusLost(evt);
            }
        });
        editar_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_telefonojTextField5ActionPerformed(evt);
            }
        });

        jSeparator79.setBackground(new java.awt.Color(0, 0, 0));

        jButton14.setText("MOSTRAR DATOS");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("GUARDAR CAMBIOS");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        jComboBox14.setForeground(new java.awt.Color(153, 153, 153));
        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione sede" }));
        jComboBox14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editar_barrio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator75)
                            .addComponent(editar_ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator78)
                            .addComponent(editar_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator77)
                            .addComponent(editar_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator79, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel46))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel45)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel45)
                    .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel46)
                .addGap(5, 5, 5)
                .addComponent(editar_barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator75, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator77, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator78, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editar_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator79, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EDITAR SEDE", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campo_direccionjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_direccionjTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_direccionjTextField4ActionPerformed

    private void editar_direccionjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_direccionjTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editar_direccionjTextField4ActionPerformed

    private void editar_telefonojTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_telefonojTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editar_telefonojTextField5ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        String ciudad = campo_ciudad.getText();
        String barrio = campo_barrio.getText();
        String direccion = campo_direccion.getText();
        String telefono = campo_telefono.getText();
        funciones.registrarSedes(barrio, direccion, ciudad, telefono);
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        funciones.creartablasede(jTable1);
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        String ciudad = buscar_sede.getText();
        funciones.creartablasedeciudad(jTable1, ciudad);        
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        String barrio = buscar_barrio.getText();
        funciones.creartablasedebarrio(jTable1, barrio);
    }//GEN-LAST:event_jButton17MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        String sede = (String) jComboBox13.getSelectedItem();
        String[] partsSede = sede.split("//");
        funciones.eliminarsede(partsSede[0], partsSede[1], partsSede[2]);
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        String sede = (String) jComboBox14.getSelectedItem();
        String ciudad = editar_ciudad.getText();
        String barrio = editar_barrio.getText();
        String direccion = editar_direccion.getText();
        String telefono = editar_telefono.getText();
        String[] parteSede = sede.split("//");
        funciones.editarSede(parteSede[0],parteSede[1],parteSede[2], barrio, direccion, ciudad, telefono);
    }//GEN-LAST:event_jButton15MouseClicked

    private void jComboBox13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox13MouseClicked
        jComboBox13.removeAllItems();
        funciones.consultar_sedes_combo(jComboBox13);
    }//GEN-LAST:event_jComboBox13MouseClicked

    private void jComboBox14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox14MouseClicked
        jComboBox14.removeAllItems();
        funciones.consultar_sedes_combo(jComboBox14);
    }//GEN-LAST:event_jComboBox14MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        String sede = (String) jComboBox14.getSelectedItem();
        String[] parteSede = sede.split("//");
        funciones.consultarSede(parteSede[0], parteSede[1], parteSede[2], editar_barrio, editar_direccion, editar_ciudad, editar_telefono);
    }//GEN-LAST:event_jButton14MouseClicked

    private void campo_ciudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_ciudadFocusGained
        if(campo_ciudad.getText().equals("Ciudad")){
            campo_ciudad.setText(null);
            campo_ciudad.requestFocus();
            // quitar place holder
            removePlaceholder(campo_ciudad);
        }
    }//GEN-LAST:event_campo_ciudadFocusGained

    private void campo_ciudadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_ciudadFocusLost
        if(campo_ciudad.getText().length() == 0){
            addPlaceholder(campo_ciudad);
            campo_ciudad.setText("Ciudad");
        }
    }//GEN-LAST:event_campo_ciudadFocusLost

    private void campo_barrioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_barrioFocusGained
        if(campo_barrio.getText().equals("Barrio")){
            campo_barrio.setText(null);
            campo_barrio.requestFocus();
            // quitar place holder
            removePlaceholder(campo_barrio);
        }
    }//GEN-LAST:event_campo_barrioFocusGained

    private void campo_barrioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_barrioFocusLost
        if(campo_barrio.getText().length() == 0){
            addPlaceholder(campo_barrio);
            campo_barrio.setText("Barrio");
        }
    }//GEN-LAST:event_campo_barrioFocusLost

    private void campo_direccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_direccionFocusGained
        if(campo_direccion.getText().equals("Dirección")){
            campo_direccion.setText(null);
            campo_direccion.requestFocus();
            // quitar place holder
            removePlaceholder(campo_direccion);
        }
    }//GEN-LAST:event_campo_direccionFocusGained

    private void campo_direccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_direccionFocusLost
        if(campo_direccion.getText().length() == 0){
            addPlaceholder(campo_direccion);
            campo_direccion.setText("Dirección");
        }
    }//GEN-LAST:event_campo_direccionFocusLost

    private void campo_telefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_telefonoFocusGained
        if(campo_telefono.getText().equals("Número de teléfono")){
            campo_telefono.setText(null);
            campo_telefono.requestFocus();
            // quitar place holder
            removePlaceholder(campo_telefono);
        }
    }//GEN-LAST:event_campo_telefonoFocusGained

    private void campo_telefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campo_telefonoFocusLost
        if(campo_telefono.getText().length() == 0){
            addPlaceholder(campo_telefono);
            campo_telefono.setText("Número de teléfono");
        }
    }//GEN-LAST:event_campo_telefonoFocusLost

    private void buscar_sedeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscar_sedeFocusGained
        if(buscar_sede.getText().equals("Ciudad de la sede")){
            buscar_sede.setText(null);
            buscar_sede.requestFocus();
            // quitar place holder
            removePlaceholder(buscar_sede);
        }
    }//GEN-LAST:event_buscar_sedeFocusGained

    private void buscar_sedeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscar_sedeFocusLost
        if(buscar_sede.getText().length() == 0){
            addPlaceholder(buscar_sede);
            buscar_sede.setText("Ciudad de la sede");
        }
    }//GEN-LAST:event_buscar_sedeFocusLost

    private void buscar_barrioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscar_barrioFocusGained
        if(buscar_barrio.getText().equals("Barrio de la sede")){
           buscar_barrio.setText(null);
           buscar_barrio.requestFocus();
            // quitar place holder
           removePlaceholder(buscar_barrio);
        }
    }//GEN-LAST:event_buscar_barrioFocusGained

    private void editar_barrioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_barrioFocusGained
        if(editar_barrio.getText().equals("Barrio")){
            editar_barrio.setText(null);
            editar_barrio.requestFocus();
            // quitar place holder
            removePlaceholder(editar_barrio);
        }
    }//GEN-LAST:event_editar_barrioFocusGained

    private void editar_barrioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_barrioFocusLost
        if(editar_barrio.getText().length() == 0){
            addPlaceholder(editar_barrio);
            editar_barrio.setText("Barrio");
        }
    }//GEN-LAST:event_editar_barrioFocusLost

    private void editar_direccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_direccionFocusGained
        if(editar_direccion.getText().equals("Dirección")){
            editar_direccion.setText(null);
            editar_direccion.requestFocus();
            // quitar place holder
            removePlaceholder(editar_direccion);
        }
    }//GEN-LAST:event_editar_direccionFocusGained

    private void editar_direccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_direccionFocusLost
        if(editar_direccion.getText().length() == 0){
           addPlaceholder(editar_direccion);
           editar_direccion.setText("Dirección");
        }
    }//GEN-LAST:event_editar_direccionFocusLost

    private void editar_ciudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_ciudadFocusGained
        if(editar_ciudad.getText().equals("Ciudad")){
            editar_ciudad.setText(null);
            editar_ciudad.requestFocus();
            // quitar place holder
            removePlaceholder(editar_ciudad);
        }
    }//GEN-LAST:event_editar_ciudadFocusGained

    private void editar_ciudadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_ciudadFocusLost
        if(editar_ciudad.getText().length() == 0){
           addPlaceholder(editar_ciudad);
           editar_ciudad.setText("Ciudad");
        }
    }//GEN-LAST:event_editar_ciudadFocusLost

    private void editar_telefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_telefonoFocusGained
        if(editar_telefono.getText().equals("Número de teléfono")){
           editar_telefono.setText(null);
           editar_telefono.requestFocus();
            // quitar place holder
           removePlaceholder(editar_telefono);
        }
    }//GEN-LAST:event_editar_telefonoFocusGained

    private void editar_telefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editar_telefonoFocusLost
        if(editar_telefono.getText().length() == 0){
           addPlaceholder(editar_telefono);
           editar_telefono.setText("Número de teléfono");
        }
    }//GEN-LAST:event_editar_telefonoFocusLost

    private void buscar_barrioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscar_barrioFocusLost
        if(buscar_barrio.getText().length() == 0){
           addPlaceholder(buscar_barrio);
           buscar_barrio.setText("Barrio de la sede");
        }
    }//GEN-LAST:event_buscar_barrioFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar_barrio;
    private javax.swing.JTextField buscar_sede;
    private javax.swing.JTextField campo_barrio;
    private javax.swing.JTextField campo_ciudad;
    private javax.swing.JTextField campo_direccion;
    private javax.swing.JTextField campo_telefono;
    private javax.swing.JTextField editar_barrio;
    private javax.swing.JTextField editar_ciudad;
    private javax.swing.JTextField editar_direccion;
    private javax.swing.JTextField editar_telefono;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator61;
    private javax.swing.JSeparator jSeparator62;
    private javax.swing.JSeparator jSeparator63;
    private javax.swing.JSeparator jSeparator64;
    private javax.swing.JSeparator jSeparator66;
    private javax.swing.JSeparator jSeparator71;
    private javax.swing.JSeparator jSeparator72;
    private javax.swing.JSeparator jSeparator73;
    private javax.swing.JSeparator jSeparator75;
    private javax.swing.JSeparator jSeparator77;
    private javax.swing.JSeparator jSeparator78;
    private javax.swing.JSeparator jSeparator79;
    private javax.swing.JSeparator jSeparator83;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
